### ISSUE TITLE
ERROR: The Compose file './docker-compose.yaml' is invalid because: Unsupported config option for services.airflow-cli: 'profiles' Invalid top-level property "x-airflow-common". Valid top-level sections for this Compose file are: version, services, networks, volumes, and extensions starting with "x-".

### ISSUE THREAD

**Issue by mbiombani** [finloop/grafana-airflow-etl#1]
which version do you use for docker-compose, because when I execute I get an error
WARNING: The AIRFLOW_UID variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services.airflow-cli: 'profiles'
Invalid top-level property "x-airflow-common". Valid top-level sections for this Compose file are: version, services, networks, volumes, and extensions starting with "x-".

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
services.airflow-scheduler.depends_on contains an invalid type, it should be an array
services.airflow-triggerer.depends_on contains an invalid type, it should be an array
services.airflow-webserver.depends_on contains an invalid type, it should be an array
services.airflow-worker.depends_on contains an invalid type, it should be an array
services.flower.depends_on contains an invalid type, it should be an array
services.airflow-cli.depends_on contains an invalid type, it should be an array
services.airflow-init.depends_on contains an invalid type, it should be an array

my docker-compose version = docker-compose version 1.26.0, build d4451659

**Comment by finloop** [comment]
Hi @mbiombani . I use:
- Docker version 20.10.13, build a224086
- docker-compose version 1.29.2, build 5becea4c

> which version do you use for docker-compose, because when I execute I get an error
WARNING: The AIRFLOW_UID variable is not set. Defaulting to a blank string.

This error is caused because `AIRFLOW_UID variable is not set`. I have it set in my `.env` file. I pushed an example to repository. 

**TO FIX** 
1. Pull this repository (i updated dockerfile)
2. Open `.env` file and set `AIRFLOW_UID` to:
```
id -u
```
This command checks your user id on linux.

Please tell me if this fixed your issues.

**Comment by mbiombani** [comment]
I updated docker-compose to the latest version and everything is fine, it works

thanks

**Comment by mbiombani** [comment]
ERROR: for flower  Cannot start service flower: unable to find user id -u: no matching entries in passwd file

**Comment by finloop** [comment]
Could you show me your .env file?
Also what system your running on?

**Comment by mbiombani** [comment]
my .env
AIRFLOW_UID=id -u
_PIP_ADDITIONAL_REQUIREMENTS='boto3 pandas scikit-learn'

ubuntu 18.04

**Comment by finloop** [comment]
Ok. You misunderstood me. Run 'id -u' in terminal and set AIRFLOW_UID to the value you get from this command. In the end my .env looked like:
```
AIRFLOW_UID=1000
_PIP_ADDITIONAL_REQUIREMENTS='boto3 pandas scikit-learn'
```
In other words:
AIRFLOW_UID=result of `id -u`

**Comment by mbiombani** [comment]
ah right the value it returns is 1000 the docker-compose up command passes without error, but only I can't access the airflow server on port 5053

**Comment by finloop** [comment]
What's the error?

**Comment by mbiombani** [comment]
This site is inaccessible10.0.0.10 does not allow connection.
Here are some tips:

Check the connection
Check the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by mbiombani** [comment]
10.0.0.10 = localhost

**Comment by mbiombani** [comment]
minio and grafana is done

**Comment by finloop** [comment]
Try:
```
docker-compose down -v
docker-compose up
```
